################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
baseURL = "/"
home = "Home"
keywords = ["Solaris Tangier", "Solar Panel Manufacturing", "PV Solar Modules", "Renewable Energy Morocco", "TOPCon Solar Panels", "HJT Technology", "PERC Solar Panels", "Africa Solar Manufacturer", "Ethical Solar Sourcing", "Tangier Free Zone", "Photovoltaic Solutions"]

# cookie consent content
consent_manage = 'Manage preferences'
consent_deny = 'Deny'
consent_allow = 'Allow'
consent_outer_message_1 = 'We would like to use '
consent_inner_message = 'third party code'
consent_outer_message_2 = ' to improve the functionality of this website.'
consent_description = 'This code gives us insight into the number of people that visit our website, where they are from and what they are clicking on.'
consent_allow_all = 'Allow all'
consent_save_preferences = 'Save preferences'

# footer content
footer_content = "Solaris Tangier is Africa's largest PV solar module manufacturer, headquartered in Tangier's Free Zone near Tanger Med port. We combine cutting-edge technology with sustainable practices to power homes, businesses, and communities across Africa and North America. Partner with us for reliable, certified solar solutions that drive a cleaner future."
copyright = "Copyright © Solaris, %s-year All rights reserved"


################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

[fr.params]
baseURL = "/fr/"
home = "Accueil"
keywords = ["GPM Parks","Énergie Solaire", "Énergie Renouvelable", "Hubs Industriels Durables", "Solaire à Grande Échelle", "GreenPower Maroc", "Parc Photovoltaïque", "Énergie Propre", "Innovation Solaire", "Énergie Verte Maroc", "Écosystèmes Industriels"]

# cookie consent content
consent_manage = 'Gérer les préférences'
consent_deny = 'Refuser'
consent_allow = 'Autoriser'
consent_outer_message_1 = 'Nous souhaitons utiliser '
consent_inner_message = 'du code tiers'
consent_outer_message_2 = ' pour améliorer le fonctionnement de ce site.'
consent_description = "Ce code nous donne un aperçu du nombre de personnes qui visitent notre site, d'où elles viennent et sur quoi elles cliquent."
consent_allow_all = 'Tout autoriser'
consent_save_preferences = 'Enregistrer'

# footer content
footer_content = "GPM Parks - Alimenter demain avec l'innovation solaire. <br>Chaque centrale solaire développée par GPM Parks contribue à réduire les émissions de gaz à effet de serre, à diminuer la dépendance aux combustibles fossiles importés, à stabiliser les coûts de l'électricité à long terme et à soutenir les objectifs du Maroc en matière d'énergies renouvelables grâce à des solutions solaires techniquement robustes, écologiquement responsables et économiquement viables."
# copyright
copyright = "Copyright © Solaris, %s-year Tous droits réservés"
